### ISSUE TITLE
Map legenda text under icons

### ISSUE THREAD

**Issue by WatskeBart** [rampage128/hombot-control#18]
Not sure if this app is still maintained, but the legenda icons on the map view are covering the text partially. See screenshot.
App is used on a Android 9 with Chrome browser

![Screenshot_20200325-172108](https://user-images.githubusercontent.com/471361/77561101-8e644900-6ebe-11ea-9d33-9e972f3e1731.jpg)

**Comment by rampage128** [comment]
Hey! Sorry for the late reply. Unfortunately the app is indeed not maintained anymore. 
https://github.com/rampage128/hombot-interface has better support of all the features (excluding android wear support).

However also hombot-interface is not very actively maintained anymore.

**Comment by WatskeBart** [comment]
Thanks for the reply though. This HomBot v3 is still a awesome sucker (pun intended 😋 )
