### ISSUE TITLE
v0.4.0-alpha - app hang up

### ISSUE THREAD

**Issue by DanielXYZ2000** [rampage128/hombot-control#8]
v0.1.0 worked fine. v0.4.0-alpha hangs up directly after it was started.
Device: Nexus 5
Android 6.0.1
Android Sicherheitspatch Ebene 1. Dez. 2015

**Comment by rampage128** [comment]
Cannot reproduce this on an emulator. But I just unboxed my "old" N5 to update it and test.

**Comment by rampage128** [comment]
Unfortunately I cannot reproduce the problem on my N5 with the same Android version. 
Did you update from 0.1 to 0.4? Or did you uninstall the old version?

If not could you please try to first uninstall the complete app and reinstall it?

**Comment by DanielXYZ2000** [comment]
Yes, I just updated from 0.1 to 0.4. Now I uninstalled the 0.4 version and reinstalled it and everything works fine. Maybe some issues with the settings. Thanks a lot - great app!!!
